name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (lowercase tag)
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}:latest"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "Image name: $IMAGE_NAME_LOWER"
          docker build -t "$IMAGE_NAME_LOWER" .

      - name: Push Docker image (lowercase tag)
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}:latest"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker push "$IMAGE_NAME_LOWER"
